### ISSUE TITLE
Unable to connect to Polygon mainnet and/or Polygon 

### ISSUE THREAD

**Issue by TriLogic** [HashLips/hashlips_nft_minting_dapp#107]
After deploying my contract to Polygon I receive the following message when running the dapp:

Error
Unsupported network.

I get this message when MetaMask is targeted at either Polygon mainnet of Polygon Mumbai

**Comment by JoeBachyEth** [comment]
Hello kindly send me a Direct message on the issues you’re experiencing for further assistance.
Thank you .

**Comment by TriLogic** [comment]
Hello. Can you help me with my minting-dapp issue on Polygon Mumbai and
Polygon Mainnet?

Andrew Friedl
(816) 806-0030

**Comment by JoeBachyEth** [comment]
I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum to help you sort this issue out right away. Click on the —> https://forum.mattic.online/ To help you sort this out right away

**Comment by TriLogic** [comment]
> I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum to help you sort this issue out right away. Click on the —> https://forum.mattic.online/ To help you sort this out right away

But I'm using the hashlips miniting-dapp straight out of the repo? Are other people successfully using the minting-dapp to connect to polygon?

**Comment by TriLogic** [comment]
I had to insert two lines at line 7 of CollectionConfig.ts and comment out the previous lines 7,8 so that it looks like this:

  testnet: Networks.polygonTestnet,
  mainnet: Networks.polygonMainnet,
  //testnet: Networks.ethereumTestnet,
  //mainnet: Networks.ethereumMainnet,

minting-dapp is not going to chat with a Polygon chain if  it's targeted at the ethereum chains.  If this was discussed in the Master Class video then I missed it.

**Comment by StrawberryHero** [comment]
Hello @TriLogic I'm having the same problem as you and I have verified my contract on polygon scan but the minting dapp says that my metamask has an unsupported network. (my metamask wallet is on the polygon network like the contract)

I have done as you suggested on your latest post but unfortunately I am still having the same problem, am I missing something here?

Thanks

**Comment by TriLogic** [comment]
> Hello @TriLogic I'm having the same problem as you and I have verified my contract on polygon scan but the minting dapp says that my metamask has an unsupported network. (my metamask wallet is on the polygon network like the contract)
> 
> I have done as you suggested on your latest post but unfortunately I am still having the same problem, am I missing something here?
> 
> Thanks

You're MetaMask wallet needs to be pointed to the correct network and you may need to build/restart the server.  ALWAYS be sure you saved the altered file before restarting the server.  MetaMask needs to have the correct networks which may/may not have been added  to it.  Hope this helps.
