### ISSUE TITLE
interaction with thirdweb

### ISSUE THREAD

**Issue by wikicrafter** [HashLips/hashlips_nft_minting_dapp#136]
it has transaction failing issues when trying to use <h2>thirdweb</h2> smartContract
would be awesome if u right down on readme file how to make  it to work.

**Comment by slavakurilyak** [comment]
I think the error is related to the minting cost or price. ThirdWeb uses Ether while Hashlips minting DApp uses Wei (smallest denomination of Ether).

Let's say you want to sell a Polygon NFT.

In ThirdWeb, the `currency` is `1` (1 MATIC).

In Hashlips minting DApp, the `cost` is `1000000000000000000` (1000000000000000000 WEI or 1 MATIC)

**Comment by wikicrafter** [comment]
Sadly it's not about that
![image](https://user-images.githubusercontent.com/22988682/177552185-889ae503-2daf-43d4-ba2f-55315d4cce65.png)

<br>
Sth strange :D 
<br>
Anyway thanks for your attention

**Comment by wikicrafter** [comment]
> I think the error is related to the minting cost or price. ThirdWeb uses Ether while Hashlips minting DApp uses Wei (smallest denomination of Ether).
> 
> Let's say you want to sell a Polygon NFT.
> 
> In ThirdWeb, the `currency` is `1` (1 MATIC).
> 
> In Hashlips minting DApp, the `cost` is `1000000000000000000` (1000000000000000000 WEI or 1 MATIC)

u can preview repo: [testzcp](https://github.com/wikicrafter/testzcp)
