### ISSUE TITLE
mint error

### ISSUE THREAD

**Issue by WangGuaGua1023** [HashLips/hashlips_nft_minting_dapp#55]
when I mint the NFT, error happans.

Error: Invalid number of parameters for "mint". Got 1 expected 2!
▶ 2 stack frames were collapsed.
claimNFTs
D:/git/hashlips_nft_minting_dapp/src/App.js:132
  129 | console.log("Gas limit: ", totalGasLimit);
  130 | setFeedback(`Minting your ${CONFIG.NFT_NAME}...`);
  131 | setClaimingNft(true);
> 132 | blockchain.smartContract.methods
      | ^  133 |   .mint(mintAmount)
  134 |   .send({
  135 |     gasLimit: String(totalGasLimit),
View compiled
onClick
D:/git/hashlips_nft_minting_dapp/src/App.js:359
  356 |   disabled={claimingNft ? 1 : 0}
  357 |   onClick={(e) => {
  358 |     e.preventDefault();
> 359 |     claimNFTs();
      | ^  360 |     getData();
  361 |   }}
  362 | >
View compiled
▶ 19 stack frames were collapsed.

**Comment by clipartinc** [comment]
Check your abi.json to make sure it matches your contract.

It's mentioned here:
https://github.com/HashLips/hashlips_nft_minting_dapp/pull/23

**Comment by WangGuaGua1023** [comment]
ok,sir. I will try

GottaMinute ***@***.***> 于2022年1月28日周五 14:14写道：
