### ISSUE TITLE
Connect button not working on MOBILE

### ISSUE THREAD

**Issue by gorkemkose** [HashLips/hashlips_nft_minting_dapp#72]
Hi, I'm creating a minting dapp using the template of nerdy coder clones. While I was simulating the website on mobile, I noticed that the connect button returns the feedback of "Install metamask" even if I have installed Metamask mobile application to my phone. Same error reproduced in nerdycoderclones.online website too. How can I solve that? Any help would be appreciated. Thanks!
Görkem

**Comment by vd4663rv** [comment]
Hi there. I have the same issue. I am just going to let it be known that the mint should be done from a desktop. should work from desktop/laptops

**Comment by gorkemkose** [comment]
Yeah, but I'm creating a project that is necessary to use mobile phones though :(

**Comment by 02jsc-2020** [comment]
you may open MetaMask App, go to setting, and copy and paste your dapp link there, you will be able to connect to your wallet rather than using chrome or safari directly

**Comment by franko-c** [comment]
Have you tried accessing the page through the built-in Metamask browser?

**Comment by gorkemkose** [comment]
Yes, but what I was asking was redirecting to the Metamask application browser when connect button is clicked from any other mobile browser. I have solved the problem using Metamask Deep Links for anyone interested. Using react-device-detect library, I checked if the browser is Metamask browser - isMetaMask- and if this not the case; I redirected to the Metamask Browser. Thank you everyone who is responded!

Görkem

**Comment by onglette** [comment]
@gorkemkose thats wonderful! can you share how to do step by step? as i would like to do the same!

**Comment by gorkemkose** [comment]
I installed the following library: https://github.com/duskload/react-device-detect
Imported using the following line:
`import { isMetaMask } from 'react-device-detect';
`
Then, using https://metamask.github.io/metamask-deeplinks/#

I clicked on "Open dAPP", pasted my website url and got the deeplink. 

I defined a variable as follows:
`const NAVIGATE = https://metamask-deep-link-i-got.com`

Since this problem only occurs in mobile, I rendered 2 different websites by checking the device window size.
`if (width > 768) {
      //Render desktop app
}else{
     //Render mobile app
}
`
Then, inside the else part, where the connect button is placed:

`{isMetaMask ? (
                      <>
                        <StyledLink style={{cursor: "pointer"}} onClick={(e) => {
                        e.preventDefault();
                        dispatch(connect());
                        getData();
                      }}
                      >
                        Connect
                        </StyledLink>
                      </>
                    ) : 
                    (
                      <>
                       <StyledLink href = {NAVIGATE}>
                         Connect
                        </StyledLink>
                      </>
                    )}`

Hope this explains!

**Comment by onglette** [comment]
@gorkemkose 

Thanks so much! This is really helpful

Will try it out later tonight :) :)

C

**Comment by yograjmeena** [comment]
@gorkemkose I am Newbie and dont  know how to install React Device detect, how to install it to the Minting Dapp, Kindly Please Explain, its very important for us, it will be Great if you send a Video of how to do it

**Comment by yograjmeena** [comment]
@gorkemkose please atleast send us the updated code file
