### ISSUE TITLE
Mint Failed after button says "Busy"

### ISSUE THREAD

**Issue by onglette** [HashLips/hashlips_nft_minting_dapp#77]
Hello,

When I click on "Mint", metamask pops up and i am able to confirm the transaction. The mint button says "busy" but then it will say failed.

![image](https://user-images.githubusercontent.com/6267658/154639632-f773f7af-700e-4aba-85ec-c11deae03b7a.png)

Any help would be appreciated

**Comment by onglette** [comment]
This is the console log

![image](https://user-images.githubusercontent.com/6267658/154706942-8823b95f-c973-4429-acde-232e4476e536.png)

**Comment by heisenbergpromotions** [comment]
what gas settings have you got? I would try higher gas

**Comment by onglette** [comment]
@heisenbergpromotions 
hello there!
i set the gas fee to   "GAS_LIMIT": 500000,

**Comment by onglette** [comment]
I increased it to:
"GAS_LIMIT": 10000000, 

And got this error
<img width="975" alt="image" src="https://user-images.githubusercontent.com/6267658/154722538-4cca3c82-03b6-4f43-ae26-4d7cf6935edc.png">
