### ISSUE TITLE
Error: Invalid number of parameters for "mint". Got 1 expected 0!

### ISSUE THREAD

**Issue by iainestera** [HashLips/hashlips_nft_minting_dapp#82]
Using a rewarded contract：https://etherscan.io/address/0x1483c67d318951ea7ffdc01c4aba798288e7835c#code
![QQ图片20220227171243](https://user-images.githubusercontent.com/79497730/155876172-70659710-ea61-4f55-95a9-639f8145497d.png)
![06](https://user-images.githubusercontent.com/79497730/155876218-1759406e-e3e5-4402-842a-1ec98344cc96.png)

**Comment by crice71** [comment]
I am having this same problem. What was the fix?
