### ISSUE TITLE
issues with app.js in minting dapp.

### ISSUE THREAD

**Issue by Negaunee0024** [HashLips/hashlips_nft_minting_dapp#88]
I have spent several days learning how to build and use merkel trees.  I have used this minting dapp before (in testing only).  The minting dapp seems to be specific to these contracts.  I made a contract with a 3 stage process.  (two whitelist stages, one public).  It would be unfortunate to not be compatible with this.  I have already doubled my time allowance that I was going to spend.  I imported my own abi from the contract in hardhat, and still won't work.  I changed  .mint(mintAmount) to  .mint(blockchain.account, mintAmount) like i've seen recommended here.  the abi is definitely right as I verified the contract already.  Thanks for any help I may receive.

**Comment by Negaunee0024** [comment]
Sorry to include my current errors in app.js.  Thanks.  If anyone solves it i'll toss them some matic;


×
TypeError: blockchain.smartContract.methods.mint is not a function
claimNFTs
C:/Users/negau/Desktop/NFTs/hashlips_nft_minting_dapp/src/App.js:132
  129 | console.log("Gas limit: ", totalGasLimit);
  130 | setFeedback(`Minting your ${CONFIG.NFT_NAME}...`);
  131 | setClaimingNft(true);
> 132 | blockchain.smartContract.methods
      | ^  133 |   .mint(blockchain.account, mintAmount)
  134 |   .send({
  135 |     gasLimit: String(totalGasLimit),
View compiled
onClick
C:/Users/negau/Desktop/NFTs/hashlips_nft_minting_dapp/src/App.js:359
  356 |   disabled={claimingNft ? 1 : 0}
  357 |   onClick={(e) => {
  358 |     e.preventDefault();
> 359 |     claimNFTs();
      | ^  360 |     getData();
  361 |   }}
  362 | >
View compiled
▶ 19 stack frames were collapsed.

**Comment by Shiva-Tzu** [comment]
Did you end up figuring this out? I've been having a similar issue. Would like to add a merkle tree and whitelist mint functionality to the dApp.
