### ISSUE TITLE
TypeError: blockchain.smartcontract.methods.mint is not a function

### ISSUE THREAD

**Issue by yograjmeena** [HashLips/hashlips_nft_minting_dapp#92]
![Screenshot (104)](https://user-images.githubusercontent.com/101491174/158514910-b648e3df-2f2f-437c-af38-55770b3640aa.png)
I am getting this error when i try to mint some nfts ### TypeError: blockchain.smartcontract.methods.mint is not a function
I don't now how to fix this issue, Kindly need urgent help on this issue

**Comment by 9kort** [comment]
I had this issue and it seemed to be connected with my ABI. Just make sure that if/when you copied your ABI from Remix, the contract above the "Publish on IPFS" button shows your contract and not the Ownable.sol. Make sure you copy and paste that ABI into the abi.json file and not the ownable. Hopefully, this works for you!

**Comment by yograjmeena** [comment]
@9kort  Thanks buddy for replying we just solve the issue, we have the different mint function in our smart contract and we change it on the Dapp.

**Comment by km-akhluk** [comment]
@9kort I got the same error & failed to fix it. Can help me?

**Comment by nsocium** [comment]
I got the same error & failed to fix it. Can help me?

**Comment by NFTapparel** [comment]
> @9kort  Thanks buddy for replying we just solve the issue, we have the different mint function in our smart contract and we change it on the Dapp.

What's the function?
